title: Peculiar Oatmeal
logo: /assets/img/weather.jpg
description: <a href = "https://www.imdb.com/title/tt9426210/"><i>Wathering With You</i></a> <br><br>Fahim Fuad Prottoy<br>Chittagong, Bangladesh<br><br>Southeast University, Dhaka<br><i>(2019 - 2023)</i>
theme: jekyll-theme-minimal
