title: Peculiar Oatmeal
logo: /assets/img/weather.jpg
description: <i>Movie - Wathering With You</i><br><br>Fahim Fuad Prottoy<br>Chittagong, Bangladesh<br><br>Southeast University<br>(2019-2023)
theme: jekyll-theme-minimal
